In [1]:
print("01-04-2026")

01-04-2026

In [2]:
print("Introduction to Python Programming")

Introduction to Python Programming

In [24]:
import pandas as pd
df = pd.read_excel(r"C:\Users\Jagatjyoti\Jagat_Code\31-03-2026\data.xlsx")
print(df.head())

            CountryName CountryCode  BirthRate  InternetUsers  \
0                 Aruba         ABW     10.244           78.9
1           Afghanistan         AFG     35.253            5.9
2                Angola         AGO     45.985           19.1
3               Albania         ALB     12.877           57.2
4  United Arab Emirates         ARE     11.044           88.0

           IncomeGroup
0          High income
1           Low income
2  Upper middle income
3  Upper middle income
4          High income

In [5]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [7]:
df['CountryCode']

0      ABW
1      AFG
2      AGO
3      ALB
4      ARE
      ...
190    YEM
191    ZAF
192    COD
193    ZMB
194    ZWE
Name: CountryCode, Length: 195, dtype: object

In [8]:
df[['CountryCode','CountryName']]

    CountryCode           CountryName
0           ABW                 Aruba
1           AFG           Afghanistan
2           AGO                Angola
3           ALB               Albania
4           ARE  United Arab Emirates
..          ...                   ...
190         YEM           Yemen, Rep.
191         ZAF          South Africa
192         COD      Congo, Dem. Rep.
193         ZMB                Zambia
194         ZWE              Zimbabwe

[195 rows x 2 columns]

In [9]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [11]:
df_cat = df[['CountryName', 'CountryCode','IncomeGroup']]
df_cat.head(1)

  CountryName CountryCode  IncomeGroup
0       Aruba         ABW  High income

In [19]:
df_num = df[['BirthRate', 'InternetUsers']]
df_num.head(1)

   BirthRate  InternetUsers
0     10.244           78.9

In [21]:
df.describe

<bound method NDFrame.describe of               CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [22]:

df_num.describe

<bound method NDFrame.describe of      BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]>

In [25]:
df.describe

<bound method NDFrame.describe of               CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [26]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [27]:
df_num.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [28]:
df_cat.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [29]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [31]:
df['InternetUsers']<2

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: InternetUsers, Length: 195, dtype: bool

In [32]:
df[df['InternetUsers']<2]

      CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
11        Burundi         BDI     44.151            1.3           Low income
52        Eritrea         ERI     34.800            0.9           Low income
55       Ethiopia         ETH     32.925            1.9           Low income
64         Guinea         GIN     37.337            1.6           Low income
117       Myanmar         MMR     18.119            1.6  Lower middle income
127         Niger         NER     49.661            1.7           Low income
154  Sierra Leone         SLE     36.729            1.7           Low income
156       Somalia         SOM     43.891            1.5           Low income
172   Timor-Leste         TLS     35.755            1.1  Lower middle income

In [37]:
df[df['BirthRate'] > 40]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
65,"Gambia, The",GMB,42.525,14.0,Low income
115,Mali,MLI,44.138,3.5,Low income
127,Niger,NER,49.661,1.7,Low income
128,Nigeria,NGA,40.045,38.0,Lower middle income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
178,Uganda,UGA,43.474,16.2,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income

In [34]:
len(df[df['InternetUsers']<2])

9

In [35]:
df[df['BirthRate'] > 40]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
65,"Gambia, The",GMB,42.525,14.0,Low income
115,Mali,MLI,44.138,3.5,Low income
127,Niger,NER,49.661,1.7,Low income
128,Nigeria,NGA,40.045,38.0,Lower middle income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
178,Uganda,UGA,43.474,16.2,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income

In [36]:
len(df[df['BirthRate'] > 40])

12

In [40]:
len( df[(df['BirthRate'] > 40) & (df['InternetUsers']<2)] )

3

In [42]:
 df[(df['BirthRate'] > 40) & (df['InternetUsers']<2)]

    CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
11      Burundi         BDI     44.151            1.3  Low income
127       Niger         NER     49.661            1.7  Low income
156     Somalia         SOM     43.891            1.5  Low income

In [44]:
 df[(df['IncomeGroup'] == 'High income') ]

               CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0                    Aruba         ABW     10.244          78.90  High income
4     United Arab Emirates         ARE     11.044          88.00  High income
5                Argentina         ARG     17.716          59.90  High income
7      Antigua and Barbuda         ATG     16.447          63.40  High income
8                Australia         AUS     13.200          83.00  High income
..                     ...         ...        ...            ...          ...
174    Trinidad and Tobago         TTO     14.590          63.80  High income
180                Uruguay         URY     14.374          57.69  High income
181          United States         USA     12.500          84.20  High income
184          Venezuela, RB         VEN     19.842          54.90  High income
185  Virgin Islands (U.S.)         VIR     10.700          45.30  High income

[67 rows x 5 columns]

In [45]:
 df[(df['IncomeGroup'] == 'Low income') ]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.90,Low income
11,Burundi,BDI,44.151,1.30,Low income
13,Benin,BEN,36.440,4.90,Low income
14,Burkina Faso,BFA,40.551,9.10,Low income
29,Central African Republic,CAF,34.076,3.50,Low income
38,Comoros,COM,34.326,6.50,Low income
52,Eritrea,ERI,34.800,0.90,Low income
55,Ethiopia,ETH,32.925,1.90,Low income
64,Guinea,GIN,37.337,1.60,Low income
65,"Gambia, The",GMB,42.525,14.00,Low income
66,Guinea-Bissau,GNB,37.503,3.10,Low income
77,Haiti,HTI,25.345,10.60,Low income
93,Cambodia,KHM,24.462,6.80,Low income
99,Liberia,LBR,35.521,3.20,Low income
111,Madagascar,MDG,34.686,3.00,Low income
115,Mali,MLI,44.138,3.50,Low income
120,Mozambique,MOZ,39.705,5.40,Low income
123,Malawi,MWI,39.459,5.05,Low income
127,Niger,NER,49.661,1.70,Low income
132,Nepal,NPL,20.923,13.30,Low income
148,Rwanda,RWA,32.689,9.00,Low income
154,Sierra Leone,SLE,36.729,1.70,Low income
156,Somalia,SOM,43.891,1.50,Low income
158,South Sudan,SSD,37.126,14.10,Low income
167,Chad,TCD,45.745,2.30,Low income
168,Togo,TGO,36.080,4.50,Low income
177,Tanzania,TZA,39.518,4.40,Low income
178,Uganda,UGA,43.474,16.20,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.20,Low income
194,Zimbabwe,ZWE,35.715,18.50,Low income

In [47]:
df['IncomeGroup'].unique()

array(['High income', 'Low income', 'Upper middle income',
       'Lower middle income'], dtype=object)

In [48]:
df['IncomeGroup'].nunique()

4

In [49]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [50]:
df.columns = ['a', 'b','c','d','e']

In [51]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [52]:
df.columns = ['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup']

In [53]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [54]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [59]:
df['mycalc'] = df['BirthRate'] * df['InternetUsers']

In [60]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,mycalc
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720

In [61]:
df=df.drop('mycalc', axis=1)

In [62]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [64]:
df=df.drop('mycalc', axis=0) # row dont have a mycalc value

KeyError: "['mycalc'] not found in axis"